### ISSUE TITLE
Can we make app content visible in browser?

### ISSUE THREAD

**Issue by alokmahor** [hrueger/AGView#44]
Electron is equivalent to chrome browser. Which is rendering angular application in it. We can say electron is rendering http://localhost:4200/

Currently I am not able to see content of http://localhost:4200/ in chrome browser the way its visible in electron app.
When I open http://localhost:4200/ I see blank black page.

Can we make small changes to this project so I can see content of http://localhost:4200/ in browser  also the way I am seeing in electron?

**Comment by hrueger** [comment]
Hi @alokmahor,
The way it works right now is that when you run the app in development mode with `npm start`, an Angular Dev Server on port 4200 is started and electron serves the app from there. When packaging, the angular app is compiled into a few .html, .js and .css files and those are packaged with the electron app. When you run the installed version, Electron just loads those packaged files.
You can find this here:     if (serve) {
        require("devtron").install();
        win.webContents.openDevTools();


        require("electron-reload")(__dirname, {
            electron: require(`${__dirname}/node_modules/electron`),
        });
        win.loadURL("http://localhost:4200");
    } else {
        win.loadURL(url.format({
            pathname: path.join(__dirname, "dist/index.html"),
            protocol: "file:",
            slashes: true,
        }));
    }

You can see the error which causes the black screen in a chrome browser in the error console:
![grafik](https://user-images.githubusercontent.com/18656830/112267358-9f809b00-8c75-11eb-98a5-5617666b047d.png)

The reason for this error is that the renderer process (the angular context) needs to communicate with the main process as obs-studio-node will only run in the main process (https://github.com/hrueger/obs-studio-node-docs/blob/9e9285106cc4450506fffee594693d5834a2f386/docs/index.md#L15), however, the UI is in the Angular (so in the renderer process). This communication is done via IPC / the remote Module of Electron. This (and the require method) does not exist in a normal browser.

I don't understand why you would want to load AGView in a Browser. You wouldn't see the Display / Projecter window there either, because this uses native windows apis and dlls which are not available in the browser (that's why you need to run osn in the electron main process).

If you want a remote controlled solution, check out the mobile app: https://play.google.com/store/apps/details?id=de.hannesrueger.agview It uses a REST API provided by AGView to communicate with the AGView. You can find the relevant code here:
Connection: https://github.com/hrueger/AGView/blob/a0f65d2d81525b311dbc63b2986692aac99dd65b/mobile/src/app/_services/connection.service.ts#L13-L35
Loading of the slides: https://github.com/hrueger/AGView/blob/a0f65d2d81525b311dbc63b2986692aac99dd65b/mobile/src/app/_components/show/show.component.ts#L20-L38
Slide Thumbnail URL: https://github.com/hrueger/AGView/blob/a0f65d2d81525b311dbc63b2986692aac99dd65b/mobile/src/app/_components/show/show.component.ts#L62
Switch to a slide: https://github.com/hrueger/AGView/blob/a0f65d2d81525b311dbc63b2986692aac99dd65b/mobile/src/app/_components/show/show.component.ts#L42

I hope this helps.

**Comment by alokmahor** [comment]
Thanks for this so elaborate explanation. 
do you have any idea on 
https://stackoverflow.com/questions/66785946/what-is-the-simplest-way-to-stream-html-canvas-content

**Comment by alokmahor** [comment]
I have sent you email mentioned on your github profile. Please see your inbox or spam. I know this issue page is not right place to write you so I wrote email.
